services:
  # RAG Service
  rag:
    build:
      context: .
      dockerfile: RAG/Dockerfile
    container_name: inf4rag-rag
    environment:
      - PORT=8001
      - RAG_PERSIST_DIR=/data
    volumes:
      - rag-data:/data
    ports:
      - "8001:8001"
    restart: unless-stopped
    networks:
      - inf4rag-network

  # Chatbot Service
  chatbot:
    build:
      context: ./chatbotbasic/WebChat
      dockerfile: Dockerfile
    container_name: inf4rag-chatbot
    environment:
      - RAG_SERVICE_URL=http://rag:8001
      - GRADIO_SERVER_PORT=7860
      - GRADIO_SERVER_NAME=0.0.0.0
    depends_on:
      - rag
    ports:
      - "7860:7860"
    restart: unless-stopped
    networks:
      - inf4rag-network

  # Prometheus Monitoring
  prometheus:
    image: docker.io/prom/prometheus:latest
    container_name: vllm-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./deploy/monitoring/prometheus/prometheus-config.yaml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - inf4rag-network
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  # Grafana Dashboard
  grafana:
    image: docker.io/grafana/grafana:latest
    container_name: vllm-grafana
    depends_on:
      - prometheus
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./deploy/monitoring/grafana:/etc/grafana/provisioning
    networks:
      - inf4rag-network

volumes:
  rag-data:
  prometheus_data:
  grafana_data:

networks:
  inf4rag-network:
    driver: bridge

